using System;
using System.Linq;
using System.Reflection;
using BepInEx.Unity.IL2CPP.Hook;
using HarmonyLib;
using Il2CppInterop.Common;
using Il2CppInterop.Runtime;
using ModCore;

public static class DetourUtils
{
	public static INativeDetour Create<T>(Type type, string methodName, Type[] parameterTypes, T to, out T original) where T : Delegate
	{
		MethodInfo method = type.GetMethod(methodName, BindingFlags.Instance | BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic, null, parameterTypes, null);
		if (method == null)
		{
			throw new InvalidOperationException($"Method {methodName} not found in type {type.FullName}");
		}
		return Create(method, to, out original);

	}
	public static INativeDetour Create<T>(Type type, string innerTypeName, string methodName, T to, out T original) where T : System.Delegate
	{
		return Create(GetInnerType(type, innerTypeName), methodName, to, out original);
	}

	public static INativeDetour Create<T>(Type type, string methodName, T to, out T original) where T : System.Delegate
	{
		return Create(type.GetMethod(methodName, AccessTools.all), to, out original);
	}

	private static INativeDetour Create<T>(MethodInfo method, T to, out T original) where T : System.Delegate
	{
		// Replacement for Bloodstone.Util.Il2CppMethodResolver.ResolveFromMethodInfo(method).
		// Uses Il2CppInteropUtils to find the NativeMethodInfoPtr_* field generated by Il2CppInterop
		// and reads the native function pointer from it.
		var nativePtrField = Il2CppInteropUtils.GetIl2CppMethodInfoPointerFieldForGeneratedMethod(method);
		if (nativePtrField == null)
		{
			throw new InvalidOperationException($"Could not resolve native method info pointer for {method.DeclaringType?.FullName}.{method.Name}");
		}

		var address = (IntPtr)nativePtrField.GetValue(null)!;
		if (address == IntPtr.Zero)
		{
			Plugin.PluginLog.LogError($"Failed to resolve address for method {method.DeclaringType.FullName}.{method.Name}");
			throw new InvalidOperationException($"Failed to resolve address for method {method.DeclaringType.FullName}.{method.Name}");
		}

		Plugin.PluginLog.LogInfo($"Detouring {method.DeclaringType.FullName}.{method.Name} at {address.ToString("X")}");
		return INativeDetour.CreateAndApply(address, to, out original);
	}

	private static Type GetInnerType(Type type, string innerTypeName)
	{
		return type.GetNestedTypes().First(x => x.Name.Contains(innerTypeName));
	}
}
